import type { Metadata } from "next";
import { Geist, Geist_Mono,Inter,Inknut_Antiqua } from "next/font/google";
import "./globals.css";
import ScrollToTop from "./components/ScrollToTop";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const inknut = Inknut_Antiqua({
  variable: "--font-inknut",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#0F1115] overflow-x-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${inknut.variable} antialiased`}
        
      >
        {children}
        <ScrollToTop />
      </body>
    </html>
  );
}
